# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Red < Formula
  desc ""
  homepage ""
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hirotake111/red/releases/download/v0.1.4/red_Darwin_x86_64.tar.gz"
      sha256 "ba9944e50f87ccd08f4ebdebf78eb1750fc9f2a641d2d76213637d9a88f8b691"

      def install
        bin.install "red"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hirotake111/red/releases/download/v0.1.4/red_Darwin_arm64.tar.gz"
      sha256 "9d0fbbcd031a3579cd18c27b22a452e73ffbe1cb8bcb9cb35169d8c4b144db09"

      def install
        bin.install "red"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hirotake111/red/releases/download/v0.1.4/red_Linux_x86_64.tar.gz"
      sha256 "77c697634925aa8923ad43c656133aac02e449ed2eec73e40f9fde89dc5af81a"
      def install
        bin.install "red"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hirotake111/red/releases/download/v0.1.4/red_Linux_arm64.tar.gz"
      sha256 "523ede4ddfded6a20331595fa3b4c650c188cbe004628895a036df216003569e"
      def install
        bin.install "red"
      end
    end
  end
end
