# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redisclient < Formula
  desc ""
  homepage ""
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hirotake111/redisclient/releases/download/v0.1.3/redisclient_Darwin_x86_64.tar.gz"
      sha256 "66036893ccd0262bfd7397442d36e0fc895251bc72c4c6cdaaab817bd1f30156"

      def install
        bin.install "redisclient"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hirotake111/redisclient/releases/download/v0.1.3/redisclient_Darwin_arm64.tar.gz"
      sha256 "0254eb3287b1617b16a21ebdd0fdad858f60d38d86ef079006c20e0643ec6d0c"

      def install
        bin.install "redisclient"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hirotake111/redisclient/releases/download/v0.1.3/redisclient_Linux_x86_64.tar.gz"
      sha256 "48f2abb1ef6e0bd4fc6d48c3bc8a5764ef83621d17f3820e65dd706bcf17e814"
      def install
        bin.install "redisclient"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hirotake111/redisclient/releases/download/v0.1.3/redisclient_Linux_arm64.tar.gz"
      sha256 "934209829ffb643dd57757b1cc72a3662ff91c493c4b56f5318877a2d56c68eb"
      def install
        bin.install "redisclient"
      end
    end
  end
end
