# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RemoteNotifier < Formula
  desc ""
  homepage ""
  version "0.1.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hirotake111/remote-notifier/releases/download/v0.1.3/remote-notifier_0.1.3_darwin_amd64.tar.gz"
    sha256 "30ff2b1b346d35e1a81d1abf03bf2cc92ecea3071e5bf97aec54d5808f0931bb"

    define_method(:install) do
      bin.install "remote-notifier"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hirotake111/remote-notifier/releases/download/v0.1.3/remote-notifier_0.1.3_darwin_arm64.tar.gz"
    sha256 "129eb4863c879c0dd4902f27b3ae2d7823902c1809a328e31e1992f5baa135d0"

    define_method(:install) do
      bin.install "remote-notifier"
    end
  end
end
