# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RemoteNotifier < Formula
  desc ""
  homepage ""
  version "0.1.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hirotake111/remote-notifier/releases/download/v0.1.3/remote-notifier_0.1.3_darwin_amd64.tar.gz"
    sha256 "0a22545b5e43c21f8c16ec54ec6de0bd90ecafca901dc876b3fdda1f7611ef0d"

    define_method(:install) do
      bin.install "remote-notifier"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hirotake111/remote-notifier/releases/download/v0.1.3/remote-notifier_0.1.3_darwin_arm64.tar.gz"
    sha256 "dca183d02a3e14c915c19457d189102a144dc28cb2f18113dca46c7a944b0316"

    define_method(:install) do
      bin.install "remote-notifier"
    end
  end
end
