# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RemoteNotifier < Formula
  desc ""
  homepage ""
  version "0.1.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hirotake111/remote-notifier/releases/download/v0.1.3/remote-notifier_0.1.3_darwin_amd64.tar.gz"
    sha256 "13b3f2775a43c2819a9c4b9c6d31f19ca430e992f7f1b31e642f0681951ee479"

    define_method(:install) do
      bin.install "remote-notifier"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hirotake111/remote-notifier/releases/download/v0.1.3/remote-notifier_0.1.3_darwin_arm64.tar.gz"
    sha256 "afaf90abc2fe7219df65c290b14f7b84c618f53c4a49284b6212efce34853a47"

    define_method(:install) do
      bin.install "remote-notifier"
    end
  end
end
